/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "./stencil-public-runtime";
export namespace Components {
    interface RfLogin {
    }
}
declare global {
    interface HTMLRfLoginElement extends Components.RfLogin, HTMLStencilElement {
    }
    var HTMLRfLoginElement: {
        prototype: HTMLRfLoginElement;
        new (): HTMLRfLoginElement;
    };
    interface HTMLElementTagNameMap {
        "rf-login": HTMLRfLoginElement;
    }
}
declare namespace LocalJSX {
    interface RfLogin {
    }
    interface IntrinsicElements {
        "rf-login": RfLogin;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "rf-login": LocalJSX.RfLogin & JSXBase.HTMLAttributes<HTMLRfLoginElement>;
        }
    }
}
